service: get-me-the-gif

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 2536
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::get-me-the-gif/*"

functions:
  get-gif:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: GET

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - node_modules/puppeteer/.local-chromium/**
    - node_modules/@ffmpeg-installer/win32-ia32/**
    - node_modules/@ffmpeg-installer/linux-ia32/**
    - node_modules/@ffmpeg-installer/win32-x64/**
    - node_modules/@ffmpeg-installer/darwin-x64/**

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: get-me-the-gif
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
